# Copyright 2024 Contributors to the Eclipse Foundation
#
# SPDX-License-Identifier: EPL-2.0

# NUCLEO-F413ZH platform options

set(OPENBSW_PLATFORM "stm32" CACHE STRING "" FORCE)
set(STM32_CHIP "STM32F413ZH" CACHE STRING "" FORCE)
set(BUILD_TARGET_RTOS "FREERTOS" CACHE STRING "Target RTOS: FREERTOS or THREADX")

set(PLATFORM_SUPPORT_CAN ON CACHE BOOL "" FORCE)
set(PLATFORM_SUPPORT_IO OFF CACHE BOOL "" FORCE)
set(PLATFORM_SUPPORT_ETHERNET OFF CACHE BOOL "" FORCE)
set(PLATFORM_SUPPORT_TRANSPORT ON CACHE BOOL "" FORCE)
set(PLATFORM_SUPPORT_UDS ON CACHE BOOL "" FORCE)
set(PLATFORM_SUPPORT_WATCHDOG OFF CACHE BOOL "" FORCE)
set(PLATFORM_SUPPORT_MPU OFF CACHE BOOL "" FORCE)
set(PLATFORM_SUPPORT_STORAGE OFF CACHE BOOL "" FORCE)
set(PLATFORM_SUPPORT_ROM_CHECK OFF CACHE BOOL "" FORCE)
